### ISSUE TITLE
[Question] Is there anyway to specify custom options during array creation ?

### ISSUE THREAD

**Issue by andrey-chilipiper** [rolehippie/mdadm#7]
Hi there,

Is there any way to specify options during array creation, f.e. I wanna specify `--write-mostly` to one of member of raid 1 ?

**Comment by tboerger** [comment]
Currently there is nothing implemented for additional arguments, but I'm open for changes.

**Comment by tboerger** [comment]
With v1.1.0 you are able to add any flag to the create command:

```
mdadm_arrays:
  - number: 0
    level: 1
    filesystem: ext4
    mountpoint: /var/lib/bar
    args:
      - --data-offset=1024
    devices:
      - /dev/sdd
      - /dev/sde
```

Thsi does not affect already existing arrays.
